# -*- coding: utf-8 -*-
"""MNIST_Fashion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11XxAImEVEuMHwmxVonLZyuwnP-5iK0mS
"""

import tensorflow as tf
print(tf.__version__)

from tensorflow import keras

mnist=keras.datasets.fashion_mnist

mnist

mnist_fashion=mnist.load_data()

mnist_fashion

(training_images,training_labels) ,(test_images,test_labels)=mnist.load_data()

import matplotlib.pyplot as plt
plt.imshow(training_images[100])
plt.axis(None)

import matplotlib.pyplot as plt
plt.imshow(training_images[0])
print(training_labels[0])
print(training_images[0])

training_images=training_images/255.0

test_images=test_images/255.0

model=tf.keras.models.Sequential([tf.keras.layers.Flatten(),
                                  tf.keras.layers.Dense(128,activation=tf.nn.relu),
                                  tf.keras.layers.Dense(10,activation=tf.nn.softmax)])

model.compile(optimizer=tf.keras.optimizers.Adam(),loss="sparse_categorical_crossentropy",metrics=['accuracy'])

model.fit(training_images,training_labels,epochs=5)

model.evaluate(test_images,test_labels)

classifications=model.predict(test_images)
print(classifications[0])

from PIL import Image
import numpy as np

test_image=Image.open("/content/download (3).png").convert('L')

test_image=test_image.resize((28,28))

image_array=np.array(test_image)

image_array=image_array/255.0

image_array=image_array.reshape(1,28,28)

model.summary()

predictions=model.predict(image_array)
print(predictions)

print(max(max(predictions)))
for i in range(10):
  if(predictions[0][i]==max(max(predictions))):
    print(i)
    euu=i

"""0 T-shirt/top

1 Trouser

2 Pullover

3 Dress

4 Coat

5 Sandal

6 Shirt

7 Sneaker

8 Bag

9 Ankle boot
"""

print(euu)

i=euu
if i==0:
  print("Shoes")
if i==1:
  print("T-shirt/top")
if i==2:
  print("Pullover")
if i==3:
  print("Dress")
if i==4:
  print("Coat")
if i==5:
  print("Sandal")
if i==6:
  print("Shirt")
if i==7:
  print("Sneaker")
if i==8:
  print("Bag")
if i==9:
  print("Ankle boot")

